# Generated by Django 4.1.7 on 2023-06-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_temperaturenew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturenew',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
